App\Domain\Entity\Item:
  type: entity

  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    type:
      type: string
      length: 100
      nullable: false

    weight:
      type: integer
      nullable: false

  manyToOne:
    items:
      targetEntity: App\Entity\Basket
      inversedBy: items